const stockSilla = [
  {
    id: 1,
    producto: "Silla Eames",
    img: `../img/sillas/sillasEames.jpg`,
    cantidad: 1,
    precio: 20000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 2,
    producto: "Silla Eames con amohadon",
    img: `../img/sillas/sillasEamesConAlmohadon.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 3,
    producto: "Silla Eames ecocuero tapizado",
    img: `../img/sillas/sillasEamesEcocueroTapizadas.jpeg`,
    cantidad: 1,
    precio: 20500,
    categoria: "silla",
    stock: true,
  },
  {
    id: 4,
    producto: "Silla Eames para niños",
    img: `../img/sillas/sillasEamesParaNiños.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 5,
    producto: "Silla ecocuero",
    img: `../img/sillas/sillasEcocuero.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 6,
    producto: "Silla eiffel",
    img: `../img/sillas/sillasEiffel.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 7,
    producto: "Silla hexagonales",
    img: `../img/sillas/sillasHexagonales.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 8,
    producto: "Silla tolix",
    img: `../img/sillas/sillasTolix.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 9,
    producto: "Silla tulip con almohadon",
    img: `../img/sillas/sillasTulipConAlmohadon.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 10,
    producto: "Silla tulip con almohadon tapizadas en lino",
    img: `../img/sillas/sillasTulipConAlmohadonTapizadasEnLino.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 11,
    producto: "Banqueta Eames",
    img: `../img/sillas/banquetasEames.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 12,
    producto: "Banqueta Tolix",
    img: `../img/sillas/banquetasTolix.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
  {
    id: 13,
    producto: "Taburete Tolix",
    img: `../img/sillas/tabuleteTolix.jpg`,
    cantidad: 1,
    precio: 21000,
    categoria: "silla",
    stock: true,
  },
];

const StockMesa = [
  {
    id: 1,
    producto: "mesa eames rectangular laqueada",
    img: `../img/mesas/mesaEamesRectangularLaqueada.jpg`,
    cantidad: 1,
    precio: 30000,
    categoria: "mesa",
    stock: true,
  },
  {
    id: 2,
    producto: "mesa eames redonda de vidrio",
    img: `../img/mesas/mesaEamesRedondaDeVidrio.jpg`,
    cantidad: 1,
    precio: 31000,
    categoria: "mesa",
    stock: true,
  },
  {
    id: 3,
    producto: "mesa eames redonda laqueada",
    img: `../img/mesas/mesaRedondaLaqueada.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "mesa",
    stock: true,
  },
  {
    id: 4,
    producto: "mesa eames para niños",
    img: `../img/mesas/mesaEamesParaNiños.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "mesa",
    stock: true,
  },
  {
    id: 5,
    producto: "mesa tulip rectangular de vidrio",
    img: `../img/mesas/mesaTulipRectangularDeVidrio.jpeg`,
    cantidad: 1,
    precio: 30500,
    categoria: "mesa",
    stock: true,
  },
];
const StockSillones = [
  {
    id: 1,
    producto: "sillon eames",
    img: `../img/sillon/sillonEames.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "sillones",
    disponibilidad: 1,
  },
  {
    id: 2,
    producto: "sillon eiffel",
    img: `../img/sillon/sillonEiffel.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "sillones",
    disponibilidad: 1,
  },
  {
    id: 3,
    producto: "sillon mecedora",
    img: `../img/sillon/sillonMecedora.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "sillones",
    disponibilidad: 1,
  },
  {
    id: 4,
    producto: "sillon tulip suizo",
    img: `../img/sillon/sillonTulipSuizo.jpg`,
    cantidad: 1,
    precio: 30500,
    categoria: "sillones",
    disponibilidad: 0,
  },
];